version: '3'

services:

  mongo:
    image: mongo:3.4.14
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    restart: unless-stopped

  mongo-scripts: 
    image: mongo-scripts
    container_name: mongo_scripts
    environment:
        - SERVER=mongo
        - PORT=27017
        - DATABASE=HANGFIRE_TUTORIAL
        - USERNAME=myuser
        - PASSWORD=pwd
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    restart: always